trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: job1
  steps:
  - script: echo Hello, Job1!
    displayName: 'Running Job1'
  - script: |
      echo testing
      echo another testing
- job: job2
  dependsOn: job1
  steps:
  - script: echo Hello, Job2!
    displayName: 'Running Job2'
  - script: |
      echo testing job2
      echo another testing job2