trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Firstjobi
    steps:
      - bash: echo my first job
  - job: Secondjob 
    steps:
      - bash: echo build first job

- stage: Dev
  jobs:
  - job: second
    steps:
      - bash: echo my second job
  - job: Secondjob
    steps:
      - bash: echo build second job
- stage: stage
  jobs:
  - job: third
    steps:
      - bash: echo my third job
  - job: thirdjob
    steps:
      - bash: echo build third job
- stage: prod
  jobs:
  - job: fourty
    steps:
      - bash: echo my fourth job
  - job: fourthjob
    steps:
      - bash: echo build fourth job
      